# Generated by Django 3.2 on 2021-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loggedin_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, unique=True)),
                ('token_expiry', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_lname', models.CharField(max_length=100, unique=True)),
                ('user_fname', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email_id', models.EmailField(max_length=254)),
                ('lastloggedin', models.DateTimeField()),
            ],
        ),
    ]
