# Generated by Django 3.2 on 2021-05-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pneumonia_data',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_api.user')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pneumonia')),
            ],
        ),
    ]
