# Generated by Django 3.1.1 on 2021-05-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0003_auto_20210503_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedin_user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
