# Generated by Django 3.2 on 2021-05-03 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_pneumonia_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pneumonia_data',
            old_name='id',
            new_name='img_id',
        ),
        migrations.RemoveField(
            model_name='loggedin_user',
            name='token_expiry',
        ),
        migrations.AddField(
            model_name='loggedin_user',
            name='loginTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='null', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastloggedin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_lname',
            field=models.CharField(max_length=100),
        ),
    ]
